#!/usr/bin/env bash

OLDPWD=`pwd`

echo -n "Symlinking custom rc files..."
ln -sf ~/git/util/.ackrc ~
ln -sf ~/git/util/.bash ~
ln -sf ~/git/util/.bashrc ~
ln -sf ~/git/util/.bash_profile ~
ln -sf ~/git/util/.bash_logout ~
ln -sf ~/git/util/.gemrc ~
ln -sf ~/git/util/.vimrc ~
echo " done"

echo -n "Symlinking custom bin files..."
ln -sf ~/git/util/bin ~
echo " done"

echo -n "Setting up solorized color scheme for dircolors..."
ln -sf ~/git/util/dircolors-solarized-dark ~/.dircolors
ln -sf ~/git/util/dircolors-solarized-dark ~/.dircolors.old
echo " done"

which xrdb > /dev/null
xrdb=$?

mkdir -p ~/.vim/colors
if [ `which wget` ]; then
  echo -n "Using wget to setup solorized color scheme for vim..."
  wget \
    --quiet \
    --output-document ~/.vim/colors/solarized.vim \
    http://github.com/altercation/vim-colors-solarized/raw/master/colors/solarized.vim
  echo " done"
  if [ "x$xrdb" == "x0" ]; then
    echo -n "Using wget to setup solorized color scheme for X..."
    wget \
      --quiet \
      --output-document ~/.Xresources \
      http://github.com/altercation/solarized/raw/master/xresources-colors-solarized/Xresources
    xrdb -merge ~/.Xresources
    echo " done"
  else
    echo "No xrdb, skipping X setup."
  fi
elif [ `which curl` ]; then
  echo -n "Using curl to setup solorized color scheme for vim..."
  curl \
    --silent \
    --output ~/.vim/colors/solarized.vim \
    http://github.com/altercation/vim-colors-solarized/raw/master/colors/solarized.vim
  echo " done"
  if [ "x$xrdb" == "x0" ]; then
    echo -n "Using curl to setup solorized color scheme for X..."
    curl \
      --silent \
      --output ~/.Xresources \
      http://github.com/altercation/solarized/raw/master/xresources-colors-solarized/Xresources
    xrdb -merge ~/.Xresources
    echo " done"
  else
    echo "No xrdb, skipping X setup."
  fi
else
  echo "No curl/wget found, setup solorized color scheme for vim/X skipped."
fi

which fc-cache > /dev/null
fc_cache=$?
which gnome-terminal gconftool-2 > /dev/null
gnome_term=$?
which mate-terminal mateconftool-2 > /dev/null
mate_term=$?
which xfce4-terminal > /dev/null
xfce_term=$?

if [ "x$fc_cache" == "x0" ]; then
  echo -n "Installing custom fonts..."
  ln -sf ~/git/util/fonts ~/.fonts
  sudo fc-cache -f
  echo " done"
  if [ "x$gnome_term" == "x0" ]; then
    echo -n "Configuring gnome-terminal to use custom fonts..."
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_system_font" --type bool false
    gconftool-2 --set "/apps/gnome-terminal/profiles/Default/font" --type string "Droid Sans Mono Dotted 9"
    echo " done"
  elif [ "x$mate_term" == "x0" ]; then
    echo -n "Configuring mate-terminal to use custom fonts..."
    mateconftool-2 --set "/apps/mate-terminal/profiles/Default/use_system_font" --type bool false
    mateconftool-2 --set "/apps/mate-terminal/profiles/Default/font" --type string "Droid Sans Mono Dotted 9"
    echo " done"
  fi
else
  echo "No fc-cache, skipping custom font installation."
fi

if [ "x$gnome_term" == "x0" ]; then
  echo -n "Configuring gnome-terminal to use solarized color scheme..."
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_background" --type bool false
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_colors" --type bool false
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/palette" --type string "#070736364242:#D3D301010202:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/background_color" --type string "#00002B2B3636"
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/foreground_color" --type string "#65657B7B8383"
  echo " done"
elif [ "x$mate_term" == "x0" ]; then
  echo -n "Configuring mate-terminal to use solarized color scheme..."
  mateconftool-2 --set "/apps/mate-terminal/profiles/Default/use_theme_background" --type bool false
  mateconftool-2 --set "/apps/mate-terminal/profiles/Default/use_theme_colors" --type bool false
  mateconftool-2 --set "/apps/mate-terminal/profiles/Default/palette" --type string "#070736364242:#D3D301010202:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"
  mateconftool-2 --set "/apps/mate-terminal/profiles/Default/background_color" --type string "#00002B2B3636"
  mateconftool-2 --set "/apps/mate-terminal/profiles/Default/foreground_color" --type string "#65657B7B8383"
  echo " done"
elif [ "x$xfce_term" == "x0" ]; then
  echo -n "Configuring xfce-terminal to use solarized color scheme..."
  mkdir -p ~/.config/Terminal
  cp ~/git/util/xfce-configs/solarized-dark.config ~/.config/Terminal/terminalrc
  echo " done"
else
  echo "No gnome, xfce or mate terminal, skipping terminal setup."
fi

echo -n "Setting up dircolors..."
cat "$HOME/.dircolors.old" | sed 's/MULTIHARDLINK/HARDLINK/' | dircolors -b > /tmp/dircolors-$USER
mv /tmp/dircolors-$USER "$HOME/.dircolors.old.compiled"
dircolors -b "$HOME/.dircolors" > /tmp/dircolors-$USER
mv /tmp/dircolors-$USER "$HOME/.dircolors.compiled"
echo " done"

echo -n "Setting up vim bundler..."
mkdir -p "$HOME/.vim/bundle"
[ -d $HOME/.vim/bundle/vundle ] && rm -rf $HOME/.vim/bundle/vundle
git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
vim -c ':BundleInstall' -c ':quitall' .foo

cd $OLDPWD
