#!/bin/sh

OLDPWD=`pwd`

ln -sf ~/git/util/.ackrc ~
ln -sf ~/git/util/.bash ~
ln -sf ~/git/util/.bashrc ~
ln -sf ~/git/util/.bash_profile ~
ln -sf ~/git/util/.bash_logout ~
ln -sf ~/git/util/.vimrc ~
ln -sf ~/git/util/bin ~
ln -sf ~/git/util/dircolors-solarized-dark ~/.dircolors

mkdir -p ~/.vim/colors
if [ `which wget` ]; then
  wget \
    --quiet \
    --no-check-certificate \
    --output-document ~/.vim/colors/solarized.vim \
    https://github.com/altercation/vim-colors-solarized/raw/master/colors/solarized.vim
elif [ `which curl` ]; then
  curl \
    --silent \
    --output ~/.vim/colors/solarized.vim \
    https://github.com/altercation/vim-colors-solarized/raw/master/colors/solarized.vim
fi

if [ `which fc-cache` ]; then
  ln -sf ~/git/util/fonts ~/.fonts
  sudo fc-cache -f
fi

if [ `which gnome-terminal` -a `which gconftool-2` ]; then
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_background" --type bool false
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/use_theme_colors" --type bool false
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/palette" --type string "#070736364242:#D3D301010202:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#58586E6E7575:#65657B7B8383:#838394949696:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3"
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/background_color" --type string "#00002B2B3636"
  gconftool-2 --set "/apps/gnome-terminal/profiles/Default/foreground_color" --type string "#65657B7B8383"
fi

if [ ! -d "$HOME/git/util-private" ]; then
  cd ~/git
  git clone git+ssh://danial@tigris.id.au/srv/git/util-private
  cd ~/git/util-private
  ./setup
fi

cd $OLDPWD
